/*
 * Copyright 2017-2018 floragunn GmbH
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 * 
 */

package com.floragunn.searchguard.tools.tlstool.tasks;

import java.io.File;
import java.io.IOException;
import java.security.KeyPair;
import java.util.ArrayList;
import java.util.List;

import org.bouncycastle.asn1.DERSequence;
import org.bouncycastle.asn1.pkcs.PKCSObjectIdentifiers;
import org.bouncycastle.asn1.x509.ExtendedKeyUsage;
import org.bouncycastle.asn1.x509.Extension;
import org.bouncycastle.asn1.x509.ExtensionsGenerator;
import org.bouncycastle.asn1.x509.KeyPurposeId;
import org.bouncycastle.asn1.x509.KeyUsage;
import org.bouncycastle.operator.ContentSigner;
import org.bouncycastle.operator.OperatorCreationException;
import org.bouncycastle.operator.jcajce.JcaContentSignerBuilder;
import org.bouncycastle.pkcs.PKCS10CertificationRequestBuilder;
import org.bouncycastle.pkcs.jcajce.JcaPKCS10CertificationRequestBuilder;

import com.floragunn.searchguard.tools.tlstool.Config;
import com.floragunn.searchguard.tools.tlstool.Context;
import com.floragunn.searchguard.tools.tlstool.ToolException;

public class CreateNodeCsr extends CreateNodeCertificateBase {

	private static final KeyPurposeId[] SERVER_AND_CLIENT_AUTH = { KeyPurposeId.id_kp_serverAuth,
			KeyPurposeId.id_kp_clientAuth };
	private static final KeyPurposeId[] SERVER_AUTH = { KeyPurposeId.id_kp_serverAuth };
	private static final KeyPurposeId[] CLIENT_AUTH = { KeyPurposeId.id_kp_clientAuth };

	private static int generatedCsrCount = 0;
	private static boolean passwordAutoGenerated = false;

	private Config.Node nodeConfig;
	private File transportCsrFile;
	private File serverCsrFile;
	private File clientCsrFile;
	private File httpCsrFile;
	private List<String> createdCsrFileNames = new ArrayList<>();

	public CreateNodeCsr(Context ctx, Config.Node nodeConfig) {
		super(ctx, nodeConfig);
		this.nodeConfig = nodeConfig;
	}

	@Override
	public void run() throws ToolException {
		String nodeFileName = getNodeFileName(nodeConfig);

		privateKeyFile = new File(ctx.getTargetDirectory(), nodeFileName + ".key");
		transportCsrFile = new File(ctx.getTargetDirectory(), nodeFileName + ".csr");
		serverPrivateKeyFile = new File(ctx.getTargetDirectory(), nodeFileName + "_server.key");
		serverCsrFile = new File(ctx.getTargetDirectory(), nodeFileName + "_server.csr");
		clientPrivateKeyFile = new File(ctx.getTargetDirectory(), nodeFileName + "_client.key");
		clientCsrFile = new File(ctx.getTargetDirectory(), nodeFileName + "_client.csr");
		httpPrivateKeyFile = new File(ctx.getTargetDirectory(), nodeFileName + "_http.key");
		httpCsrFile = new File(ctx.getTargetDirectory(), nodeFileName + "_http.csr");
		configSnippetFile = new File(ctx.getTargetDirectory(), nodeFileName + "_elasticsearch_config_snippet.yml");

		boolean splitEku = isSplitEku();

		File[] filesToCheck = splitEku
				? new File[] { serverPrivateKeyFile, serverCsrFile, clientPrivateKeyFile, clientCsrFile, httpPrivateKeyFile,
						httpCsrFile }
				: new File[] { privateKeyFile, transportCsrFile, httpPrivateKeyFile, httpCsrFile };

		if (!checkFileOverwrite("certificate", nodeConfig.getDn(), filesToCheck)) {
			return;
		}

		if (splitEku) {
			String serverPrivateKeyPassword = createCsr(serverPrivateKeyFile, serverCsrFile, resolveServerDn(nodeConfig),
					"node server", SERVER_AUTH, true);

			nodeResultConfig.setTransportServerPemKeyFilePath(serverPrivateKeyFile.getPath());
			nodeResultConfig.setTransportServerPemKeyPassword(serverPrivateKeyPassword);
			nodeResultConfig.setTransportServerPemTrustedCasFilePath("<add path to trusted ca>");
			nodeResultConfig.setTransportServerPemCertFilePath(
					"<path to transport server certificate for " + nodeFileName + ">");

			String clientPrivateKeyPassword = createCsr(clientPrivateKeyFile, clientCsrFile, resolveClientDn(nodeConfig),
					"node client", CLIENT_AUTH, true);

			nodeResultConfig.setTransportClientPemKeyFilePath(clientPrivateKeyFile.getPath());
			nodeResultConfig.setTransportClientPemKeyPassword(clientPrivateKeyPassword);
			nodeResultConfig.setTransportClientPemTrustedCasFilePath("<add path to trusted ca>");
			nodeResultConfig.setTransportClientPemCertFilePath(
					"<path to transport client certificate for " + nodeFileName + ">");
		} else {
			String privateKeyPassword = createCsr(privateKeyFile, transportCsrFile, nodeConfig.getDn(), "node",
					SERVER_AND_CLIENT_AUTH, true);

			nodeResultConfig.setTransportPemKeyFilePath(privateKeyFile.getPath());
			nodeResultConfig.setTransportPemKeyPassword(privateKeyPassword);
			nodeResultConfig.setTransportPemTrustedCasFilePath("<add path to trusted ca>");
			nodeResultConfig.setTransportPemCertFilePath("<path to transport certificate for " + nodeFileName + ">");
		}

		if (ctx.getConfig().getDefaults().isHttpsEnabled()) {
			if (ctx.getConfig().getDefaults().isReuseTransportCertificatesForHttp()) {
				addTransportCertificateToConfigAsHttpCertificate();
			} else {
				String httpPrivateKeyPassword = createCsr(httpPrivateKeyFile, httpCsrFile, nodeConfig.getDn(), "HTTP",
						SERVER_AUTH, false);

				nodeResultConfig.setHttpPemKeyFilePath(httpPrivateKeyFile.getPath());
				nodeResultConfig.setHttpPemKeyPassword(httpPrivateKeyPassword);
				nodeResultConfig.setHttpPemTrustedCasFilePath("<add path to trusted ca>");
				nodeResultConfig.setHttpPemCertFilePath("<path to HTTP certificate for " + nodeFileName + ">");
			}
		} else {
			nodeResultConfig.setHttpsEnabled(false);
		}

		addOutputFile(configSnippetFile, createConfigSnippetComment(), createConfigSnippet());
	}

	private String createConfigSnippetComment() {
		return "# This is a configuration snippet for the node " + getNodeFileName(nodeConfig) + "\n"
				+ "# Before you can proceed with configuration, you need to pass the generated signing request which can be found in the\n"
				+ "# file " + String.join(", ", createdCsrFileNames)
				+ " to your PKI in order to get the actual certificates.\n"
				+ "# If you do not have a PKI, you can use this tool with the options --create-ca and --create-cert to create a self signed CA\n"
				+ "# and sign the certificates with that CA.\n\n"
				+ "# The generated certificates need to be copied to the config directory of the node's ElasticSearch installation.\n"
				+ "# Furthermore, the private key files (with the suffix .key) generated by this tool need to be copied to that directory\n"
				+ "# as well.\n\n"
				+ "# This config snippet needs to be inserted into the file elasticsearch.yml which can be also found in the config dir.\n"
				+ "# If the config file already contains SearchGuard configuration, this needs to be replaced.\n"
				+ "# References to the PEM files for certificates need to be adjusted to match the names of the generated certificates.\n\n"
				+ "# Please refer to http://docs.search-guard.com/latest/configuring-tls for further configuration of your installation.\n\n\n";
	}

	private String createCsr(File keyFile, File csrFile, String dn, String role, KeyPurposeId[] extendedKeyUsage,
			boolean includeOidInSan) throws ToolException {
		try {
			KeyPair nodeKeyPair = generateKeyPair(nodeConfig);

			PKCS10CertificationRequestBuilder builder = new JcaPKCS10CertificationRequestBuilder(createDn(dn, role),
					nodeKeyPair.getPublic());

			ExtensionsGenerator extensionsGenerator = new ExtensionsGenerator();

			extensionsGenerator.addExtension(Extension.keyUsage, true,
					new KeyUsage(KeyUsage.digitalSignature | KeyUsage.nonRepudiation | KeyUsage.keyEncipherment));

			extensionsGenerator.addExtension(Extension.extendedKeyUsage, true, new ExtendedKeyUsage(extendedKeyUsage));

			extensionsGenerator.addExtension(Extension.subjectAlternativeName, false,
					new DERSequence(createSubjectAlternativeNameList(includeOidInSan)));

			builder.addAttribute(PKCSObjectIdentifiers.pkcs_9_at_extensionRequest, extensionsGenerator.generate());

			JcaContentSignerBuilder csBuilder = new JcaContentSignerBuilder(
					ctx.getConfig().getDefaults().getSignatureAlgorithm());
			ContentSigner signer = csBuilder.build(nodeKeyPair.getPrivate());
			org.bouncycastle.pkcs.PKCS10CertificationRequest csr = builder.build(signer);

			String privateKeyPassword = getPassword(nodeConfig.getPkPassword());

			addEncryptedOutputFile(keyFile, privateKeyPassword, nodeKeyPair.getPrivate());
			addOutputFile(csrFile, csr);
			createdCsrFileNames.add(csrFile.getName());

			generatedCsrCount++;

			if (isPasswordAutoGenerationEnabled(nodeConfig.getPkPassword())) {
				passwordAutoGenerated = true;
			}

			return privateKeyPassword;
		} catch (OperatorCreationException | IOException e) {
			throw new ToolException("Error while composing " + role + " certificate signing request for " + nodeConfig, e);
		}
	}

	public static int getGeneratedCsrCount() {
		return generatedCsrCount;
	}

	public static boolean isPasswordAutoGenerated() {
		return passwordAutoGenerated;
	}

	private void addTransportCertificateToConfigAsHttpCertificate() {
		if (isSplitEku()) {
			nodeResultConfig.setHttpPemCertFilePath(nodeResultConfig.getTransportServerPemCertFilePath());
			nodeResultConfig.setHttpPemKeyFilePath(nodeResultConfig.getTransportServerPemKeyFilePath());
			nodeResultConfig.setHttpPemKeyPassword(nodeResultConfig.getTransportServerPemKeyPassword());
			nodeResultConfig.setHttpPemTrustedCasFilePath(nodeResultConfig.getTransportServerPemTrustedCasFilePath());
		} else {
			nodeResultConfig.setHttpPemCertFilePath(nodeResultConfig.getTransportPemCertFilePath());
			nodeResultConfig.setHttpPemKeyFilePath(nodeResultConfig.getTransportPemKeyFilePath());
			nodeResultConfig.setHttpPemKeyPassword(nodeResultConfig.getTransportPemKeyPassword());
			nodeResultConfig.setHttpPemTrustedCasFilePath(nodeResultConfig.getTransportPemTrustedCasFilePath());
		}
	}
}
